apiVersion: v1
kind: Service
metadata:
  name: {{ include "nekocafe.fullname" . }}-member
  labels:
    {{- include "nekocafe.labels" . | nindent 4 }}
    app.kubernetes.io/component: member
spec:
  type: {{ .Values.services.member.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: member
  ports:
    - name: http
      port: {{ .Values.services.member.service.port }}
      targetPort: {{ .Values.services.member.containerPort }}
